// Realistic Indian Tech Jobs Dataset
const jobsData = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
    description: "Join Amazon's engineering team as an SDE Intern. Work on scalable systems and learn from experienced engineers. Strong problem-solving skills required. 6-month internship with potential for full-time conversion."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "3.5–4 LPA",
    applyUrl: "https://infosys.com/careers/get",
    description: "Infosys is hiring fresh graduates for our training program. Comprehensive 3-month training followed by project deployment. Excellent learning opportunities in enterprise software development."
  },
  {
    id: 3,
    title: "Frontend Developer Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://razorpay.com/jobs/frontend-intern",
    description: "Build beautiful payment interfaces at India's leading fintech. Work with React and modern frontend tools. Collaborate with designers and backend teams to ship features used by millions."
  },
  {
    id: 4,
    title: "Junior Backend Developer",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "6–8 LPA",
    applyUrl: "https://flipkart.com/careers/backend-dev",
    description: "Join Flipkart's backend team to build scalable e-commerce systems. Work on microservices architecture and handle millions of transactions. Great mentorship and growth opportunities."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "TCS",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "SQL"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://tcs.com/careers/qa-intern",
    description: "Learn software testing at TCS. Work on enterprise applications and gain hands-on experience with automation tools. Training provided for freshers with good analytical skills."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://swiggy.com/careers/data-analyst",
    description: "Analyze food delivery data and generate insights. Work with product and operations teams. Learn data visualization and statistical analysis in a fast-paced environment."
  },
  {
    id: 7,
    title: "Java Developer",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "4–6 LPA",
    applyUrl: "https://wipro.com/careers/java-dev",
    description: "Develop enterprise Java applications for global clients. Work on Spring Boot microservices and cloud deployments. Excellent training and certification opportunities provided."
  },
  {
    id: 8,
    title: "React Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–15 LPA",
    applyUrl: "https://phonepe.com/careers/react-dev",
    description: "Build India's most-used payment app. Work on high-performance React applications serving 400M+ users. Collaborate with product teams to create seamless user experiences."
  },
  {
    id: 9,
    title: "Python Developer",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://zoho.com/careers/python-dev",
    description: "Join Zoho's product development team. Build SaaS applications used by millions worldwide. Work in a product-focused environment with strong engineering culture and no client pressure."
  },
  {
    id: 10,
    title: "Full Stack Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["JavaScript", "Node.js", "React"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://cred.club/careers/fullstack-intern",
    description: "Build premium fintech experiences at CRED. Work across the stack on features for India's most creditworthy users. High-quality codebase and excellent mentorship from senior engineers."
  },
  {
    id: 11,
    title: "DevOps Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Linux", "Docker", "AWS"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://paytm.com/careers/devops-intern",
    description: "Learn DevOps at scale with Paytm. Work on CI/CD pipelines, containerization, and cloud infrastructure. Gain hands-on experience with industry-standard tools and practices."
  },
  {
    id: 12,
    title: "Android Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Kotlin", "Android SDK", "MVVM"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "8–12 LPA",
    applyUrl: "https://juspay.in/careers/android-dev",
    description: "Build payment SDKs used by top Indian apps. Work on performance-critical Android code. Solve challenging problems in mobile payments and security."
  },
  {
    id: 13,
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Communication"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "4–4.5 LPA",
    applyUrl: "https://accenture.com/careers/get",
    description: "Join Accenture's technology consulting practice. Work with Fortune 500 clients on digital transformation projects. Comprehensive training and global exposure opportunities."
  },
  {
    id: 14,
    title: "UI/UX Design Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Figma", "UI Design", "Prototyping"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://freshworks.com/careers/design-intern",
    description: "Design beautiful SaaS products at Freshworks. Work with product teams to create intuitive user experiences. Learn from experienced designers in a collaborative environment."
  },
  {
    id: 15,
    title: "Backend Engineer",
    company: "Capgemini",
    location: "Pune",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "MongoDB", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "7–10 LPA",
    applyUrl: "https://capgemini.com/careers/backend-eng",
    description: "Build scalable backend systems for global clients. Work on modern tech stack with microservices architecture. Opportunity to work on diverse projects across industries."
  },
  {
    id: 16,
    title: "Machine Learning Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "TensorFlow", "Machine Learning"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://ibm.com/careers/ml-intern",
    description: "Work on AI/ML projects at IBM Research. Apply machine learning algorithms to real-world problems. Access to cutting-edge research and mentorship from PhD researchers."
  },
  {
    id: 17,
    title: "Software Engineer",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Oracle DB", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "5–7 LPA",
    applyUrl: "https://oracle.com/careers/software-eng",
    description: "Develop enterprise database and cloud solutions. Work on Oracle's flagship products used by Fortune 500 companies. Strong engineering culture with focus on quality and innovation."
  },
  {
    id: 18,
    title: "Frontend Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Angular", "TypeScript", "SAPUI5"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "9–13 LPA",
    applyUrl: "https://sap.com/careers/frontend-dev",
    description: "Build enterprise software interfaces at SAP. Work on modern frontend frameworks and SAP's design system. Collaborate with global teams on products used by thousands of enterprises."
  },
  {
    id: 19,
    title: "Data Science Intern",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Pandas", "Statistics"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://cognizant.com/careers/ds-intern",
    description: "Learn data science in a corporate environment. Work on client projects involving data analysis and visualization. Training provided in advanced analytics and machine learning."
  },
  {
    id: 20,
    title: "iOS Developer",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Swift", "iOS SDK", "UIKit"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "8–11 LPA",
    applyUrl: "https://dell.com/careers/ios-dev",
    description: "Develop iOS applications for Dell's enterprise solutions. Work on apps used by sales teams and customers globally. Modern development practices and continuous learning opportunities."
  },
  {
    id: 21,
    title: "Cloud Engineer Intern",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["AWS", "Linux", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/cloud-intern",
    description: "Work on AWS cloud infrastructure. Learn about distributed systems, networking, and cloud services. Hands-on experience with the world's leading cloud platform."
  },
  {
    id: 22,
    title: "Quality Assurance Engineer",
    company: "Infosys",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Selenium", "Java", "API Testing"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://infosys.com/careers/qa-engineer",
    description: "Ensure software quality for enterprise applications. Work on test automation frameworks and CI/CD integration. Learn industry best practices in software testing."
  },
  {
    id: 23,
    title: "Product Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://flipkart.com/careers/product-analyst",
    description: "Analyze product metrics and user behavior. Work with product managers to drive data-informed decisions. Learn A/B testing and experimentation in e-commerce."
  },
  {
    id: 24,
    title: "Cybersecurity Intern",
    company: "TCS",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Network Security", "Ethical Hacking", "Linux"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://tcs.com/careers/security-intern",
    description: "Learn cybersecurity at TCS. Work on security assessments and vulnerability testing. Training in ethical hacking and security certifications provided."
  },
  {
    id: 25,
    title: "Full Stack Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "12–18 LPA",
    applyUrl: "https://razorpay.com/jobs/fullstack-dev",
    description: "Build end-to-end payment solutions. Work on both frontend and backend of India's leading payment gateway. Fast-paced fintech environment with high ownership and impact."
  },
  {
    id: 26,
    title: "Mobile App Developer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React Native", "JavaScript", "Mobile Development"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "10–14 LPA",
    applyUrl: "https://swiggy.com/careers/mobile-dev",
    description: "Build Swiggy's mobile apps used by millions daily. Work on performance optimization and new features. Collaborate with design and product teams in a fast-growing startup."
  },
  {
    id: 27,
    title: "Backend Developer Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Spring Boot", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://phonepe.com/careers/backend-intern",
    description: "Work on payment backend systems at scale. Learn microservices architecture and distributed systems. Mentorship from experienced engineers building India's payment infrastructure."
  },
  {
    id: 28,
    title: "Software Developer",
    company: "Wipro",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["C++", "Data Structures", "Algorithms"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "4–5.5 LPA",
    applyUrl: "https://wipro.com/careers/software-dev",
    description: "Develop software solutions for global clients. Work on diverse projects across domains. Strong focus on problem-solving and algorithmic thinking."
  },
  {
    id: 29,
    title: "AI/ML Engineer",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Python", "Machine Learning", "Deep Learning"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "8–12 LPA",
    applyUrl: "https://zoho.com/careers/ml-engineer",
    description: "Build AI features for Zoho's product suite. Work on NLP, computer vision, and recommendation systems. Research-oriented environment with focus on practical ML applications."
  },
  {
    id: 30,
    title: "Graduate Trainee Engineer",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3.5–4.5 LPA",
    applyUrl: "https://paytm.com/careers/gte",
    description: "Join Paytm's engineering team as a trainee. Comprehensive training program followed by project assignments. Work on fintech products serving millions of users."
  },
  {
    id: 31,
    title: "Site Reliability Engineer",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "AWS", "Monitoring"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "15–20 LPA",
    applyUrl: "https://cred.club/careers/sre",
    description: "Ensure reliability of CRED's infrastructure. Work on observability, incident management, and automation. High-impact role in a premium fintech company."
  },
  {
    id: 32,
    title: "Automation Test Engineer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Selenium", "Python", "API Testing"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "5–7 LPA",
    applyUrl: "https://juspay.in/careers/automation-test",
    description: "Build test automation frameworks for payment systems. Ensure quality of mission-critical payment infrastructure. Learn testing best practices in fintech."
  },
  {
    id: 33,
    title: "Technical Support Intern",
    company: "Accenture",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Communication", "Problem Solving", "Basic IT"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://accenture.com/careers/support-intern",
    description: "Provide technical support for enterprise applications. Learn troubleshooting and customer interaction skills. Pathway to technical consulting roles."
  },
  {
    id: 34,
    title: "Data Engineer",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Spark", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "9–13 LPA",
    applyUrl: "https://freshworks.com/careers/data-engineer",
    description: "Build data pipelines for SaaS analytics. Work with big data technologies and cloud platforms. Enable data-driven decision making across the organization."
  },
  {
    id: 35,
    title: "Security Engineer",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Security", "Penetration Testing", "OWASP"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "8–11 LPA",
    applyUrl: "https://capgemini.com/careers/security-eng",
    description: "Secure enterprise applications for global clients. Conduct security assessments and implement security controls. Work with latest security tools and frameworks."
  },
  {
    id: 36,
    title: "Research Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Research", "Python", "Mathematics"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://ibm.com/careers/research-intern",
    description: "Work on cutting-edge research projects at IBM Research. Opportunity to publish papers and work with PhD researchers. Focus areas include AI, quantum computing, and cloud."
  },
  {
    id: 37,
    title: "Database Administrator",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Oracle DB", "SQL", "Performance Tuning"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "5–7 LPA",
    applyUrl: "https://oracle.com/careers/dba",
    description: "Manage and optimize Oracle databases. Learn database administration, backup/recovery, and performance tuning. Work with enterprise-scale database systems."
  },
  {
    id: 38,
    title: "Solutions Architect Intern",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SAP", "Business Analysis", "Communication"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://sap.com/careers/architect-intern",
    description: "Learn enterprise solution architecture at SAP. Work with consultants on client projects. Understand business processes and technical implementation."
  },
  {
    id: 39,
    title: "Business Analyst Intern",
    company: "Cognizant",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Excel", "SQL", "Business Analysis"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹18k–₹28k/month Internship",
    applyUrl: "https://cognizant.com/careers/ba-intern",
    description: "Bridge business and technology as a BA intern. Learn requirements gathering and documentation. Work on real client projects in various industries."
  },
  {
    id: 40,
    title: "Network Engineer",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Networking", "Cisco", "TCP/IP"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "4.5–6 LPA",
    applyUrl: "https://dell.com/careers/network-eng",
    description: "Design and maintain network infrastructure. Work with enterprise networking equipment and protocols. Opportunity to earn networking certifications."
  },
  {
    id: 41,
    title: "Content Developer Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Technical Writing", "Documentation", "Communication"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/content-intern",
    description: "Create technical documentation for AWS services. Write clear and concise content for developers. Learn technical writing best practices from experienced writers."
  },
  {
    id: 42,
    title: "Systems Engineer",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Linux"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3.5–4 LPA",
    applyUrl: "https://infosys.com/careers/systems-eng",
    description: "Join Infosys as a Systems Engineer. Work on enterprise software development and maintenance. Comprehensive training and career growth opportunities."
  },
  {
    id: 43,
    title: "Game Developer Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Unity", "C#", "Game Development"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://flipkart.com/careers/game-dev",
    description: "Build gamification features for Flipkart's app. Work on interactive experiences and rewards systems. Learn game development in an e-commerce context."
  },
  {
    id: 44,
    title: "Blockchain Developer",
    company: "TCS",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Blockchain", "Solidity", "Web3"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "7–10 LPA",
    applyUrl: "https://tcs.com/careers/blockchain-dev",
    description: "Work on blockchain solutions for enterprise clients. Develop smart contracts and decentralized applications. Learn emerging blockchain technologies."
  },
  {
    id: 45,
    title: "Performance Engineer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Performance Testing", "JMeter", "Monitoring"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–14 LPA",
    applyUrl: "https://razorpay.com/jobs/performance-eng",
    description: "Ensure Razorpay's systems perform at scale. Conduct load testing and optimize system performance. Critical role in maintaining payment infrastructure reliability."
  },
  {
    id: 46,
    title: "Technical Writer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Technical Writing", "Documentation", "APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "5–7 LPA",
    applyUrl: "https://swiggy.com/careers/tech-writer",
    description: "Document Swiggy's APIs and internal tools. Create clear technical documentation for developers. Work closely with engineering teams."
  },
  {
    id: 47,
    title: "Platform Engineer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "Docker", "CI/CD"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–16 LPA",
    applyUrl: "https://phonepe.com/careers/platform-eng",
    description: "Build and maintain PhonePe's platform infrastructure. Work on containerization, orchestration, and developer tools. Enable engineering teams to ship faster."
  },
  {
    id: 48,
    title: "ERP Consultant Trainee",
    company: "Wipro",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SAP", "Business Processes", "Communication"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3.5–4.5 LPA",
    applyUrl: "https://wipro.com/careers/erp-trainee",
    description: "Learn ERP consulting with SAP implementation projects. Training in business processes and SAP modules. Client-facing role with travel opportunities."
  },
  {
    id: 49,
    title: "Salesforce Developer",
    company: "Cognizant",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Salesforce", "Apex", "Lightning"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "5–7 LPA",
    applyUrl: "https://cognizant.com/careers/salesforce-dev",
    description: "Develop Salesforce solutions for enterprise clients. Learn CRM customization and integration. Salesforce certification training provided."
  },
  {
    id: 50,
    title: "Product Manager Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Product Management", "Analytics", "Communication"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://flipkart.com/careers/pm-intern",
    description: "Learn product management at India's leading e-commerce company. Work on features impacting millions of users. Collaborate with engineering, design, and business teams."
  },
  {
    id: 51,
    title: "Embedded Systems Engineer",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["C", "Embedded C", "RTOS"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "6–9 LPA",
    applyUrl: "https://dell.com/careers/embedded-eng",
    description: "Work on firmware for Dell hardware products. Develop low-level software for embedded systems. Opportunity to work on cutting-edge hardware technology."
  },
  {
    id: 52,
    title: "Marketing Analyst Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Excel", "SQL", "Marketing Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/marketing-analyst",
    description: "Analyze marketing campaigns and customer data. Support marketing teams with data-driven insights. Learn digital marketing analytics at scale."
  },
  {
    id: 53,
    title: "Systems Administrator",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Linux", "Windows Server", "Networking"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://infosys.com/careers/sysadmin",
    description: "Manage IT infrastructure for enterprise clients. Work on server administration and network management. Learn enterprise IT operations."
  },
  {
    id: 54,
    title: "Growth Engineer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["JavaScript", "A/B Testing", "Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "11–15 LPA",
    applyUrl: "https://razorpay.com/jobs/growth-eng",
    description: "Drive product growth through experimentation. Build features to improve conversion and retention. Work at the intersection of engineering and product."
  },
  {
    id: 55,
    title: "Video Editor Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Video Editing", "Adobe Premiere", "After Effects"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://swiggy.com/careers/video-editor",
    description: "Create video content for Swiggy's marketing campaigns. Work on social media content and brand videos. Creative role in a fast-growing startup."
  },
  {
    id: 56,
    title: "Integration Engineer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["APIs", "Java", "Integration"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–8 LPA",
    applyUrl: "https://phonepe.com/careers/integration-eng",
    description: "Integrate PhonePe with merchant systems and banks. Work on API development and third-party integrations. Critical role in payment ecosystem."
  },
  {
    id: 57,
    title: "Scrum Master",
    company: "Wipro",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Agile", "Scrum", "Project Management"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "7–10 LPA",
    applyUrl: "https://wipro.com/careers/scrum-master",
    description: "Facilitate agile teams and remove blockers. Coach teams on agile practices. Work with multiple teams on enterprise projects."
  },
  {
    id: 58,
    title: "Computer Vision Engineer",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Python", "OpenCV", "Deep Learning"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "9–13 LPA",
    applyUrl: "https://zoho.com/careers/cv-engineer",
    description: "Build computer vision features for Zoho products. Work on image processing and object detection. Research-oriented role with practical applications."
  },
  {
    id: 59,
    title: "HR Tech Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["HR", "Excel", "Communication"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://paytm.com/careers/hr-intern",
    description: "Support HR operations and recruitment. Learn HR processes in a tech company. Work on employee engagement initiatives."
  },
  {
    id: 60,
    title: "Release Engineer",
    company: "CRED",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["CI/CD", "Jenkins", "Git"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–16 LPA",
    applyUrl: "https://cred.club/careers/release-eng",
    description: "Manage release pipelines and deployment processes. Ensure smooth and reliable software releases. Work with engineering teams to improve deployment velocity."
  }
];
